services:

    tart_monitor:
        build: 
            context: ./
        volumes:
            -   ~/tart_monitor_store:/data
        ports: 
            - 8000:8000
        environment:
            - DB_ROOT=/data
        restart: always
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "10m"
